---
- name: base_install
  hosts: main
  tasks:
     - name: Update apt
       command: "sudo apt update && sudo apt upgrade"
     - name: Add Curl
       command: "sudo apt install curl"
     - name: Check Version
       command: "curl --version"