---
- name: pull k3s configs
  hosts: main
  gather_facts: no
  tasks:
    - name: check current user
      shell: whoami
    - name: pull file
      become: yes
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /Users/james.cooper/.kube/local_k3s/{{ inventory_hostname }}/k3s.yaml
        flat: yes